# Generated by Django 6.0.1 on 2026-01-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('allowed_territory', models.TextField(help_text='Comma-separated codes (e.g. IN,US)')),
                ('expiry_date', models.DateField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='contracts/')),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('location', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=10)),
                ('breach_type', models.CharField(blank=True, choices=[('PIRACY', 'Piracy (Unauthorized Site)'), ('TERRITORY', 'Territory Breach')], max_length=20, null=True)),
                ('html_hash', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
