# Generated by Django 6.0.1 on 2026-01-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='official_runtime',
            field=models.IntegerField(default=0, help_text='Official runtime in minutes'),
        ),
    ]
