import os
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import simpleSplit
from django.conf import settings

def generate_notice_pdf(violation_id, legal_text):
    """
    Creates a PDF file for the given violation.
    Returns the file path.
    """
    
    # 1. Define File Path
    filename = f"Notice_Violation_{violation_id}.pdf"
    save_dir = os.path.join(settings.MEDIA_ROOT, 'notices')
    os.makedirs(save_dir, exist_ok=True)
    file_path = os.path.join(save_dir, filename)

    # 2. Create Canvas
    c = canvas.Canvas(file_path, pagesize=letter)
    width, height = letter

    # 3. Add Header
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 50, "OFFICIAL DMCA CEASE & DESIST NOTICE")
    
    c.setFont("Helvetica", 10)
    c.drawString(50, height - 70, "Generated by SentinAL Enforcement Engine")
    c.line(50, height - 80, width - 50, height - 80) # Horizontal line

    # 4. Add Body Text (Text Wrapping Logic)
    text_object = c.beginText(50, height - 120)
    text_object.setFont("Helvetica", 12)
    
    # Split text into lines that fit the width (margin 100px)
    max_width = width - 100
    lines = simpleSplit(legal_text, "Helvetica", 12, max_width)

    for line in lines:
        text_object.textLine(line)

    c.drawText(text_object)

    # 5. Footer
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(50, 30, "This document is electronically generated and court admissible under IT Act 2000.")
    
    c.save()
    return file_path